name: 'Push to Lokalise'
description: 'GitHub action to upload changed translation files in the base language from your GitHub repository to Lokalise TMS.'
author: 'Lokalise Group, Ilya Krukowski'
inputs:
  api_token:
    description: 'API token for Lokalise with read/write permissions'
    required: true
    secret: true
  project_id:
    description: 'Project ID for Lokalise'
    required: true
  base_lang:
    description: 'Base language (e.g., en, fr_FR)'
    required: true
    default: 'en'
  translations_path:
    description: 'Paths to translation files'
    required: true
    default: |
      locales
  file_format:
    description: 'Format of the translation files (e.g., json). Find all supported file formats at https://developers.lokalise.com/reference/api-file-formats'
    required: true
    default: 'json'
  additional_params:
    description: 'Additional parameters for Lokalise CLI on push. Find all supported options at https://github.com/lokalise/lokalise-cli-2-go/blob/main/docs/lokalise2_file_upload.md'
    required: false
    default: ''
  flat_naming:
    description: 'Use flat naming convention (true/false). If true, expects files like locales/en.json instead of locales/en/file.json'
    required: false
    default: false
  max_retries:
    description: 'Maximum number of retries on rate limit errors'
    required: false
    default: 3
  sleep_on_retry:
    description: 'Number of seconds to sleep before retrying'
    required: false
    default: 1
  upload_timeout:
    description: 'Timeout for the upload operation (in seconds)'
    required: false
    default: 120
  upload_poll_timeout:
    description: 'Timeout for the upload poll operation (in seconds)'
    required: false
    default: 120
permissions:
  contents: write
branding:
  icon: 'upload-cloud'
  color: 'green'

runs:
  using: "composite"
  steps:
    - name: Set translation paths
      id: translation-paths
      shell: bash
      env:
        TRANSLATIONS_PATH: "${{ inputs.translations_path }}"
        FLAT_NAMING: "${{ inputs.flat_naming }}"
        BASE_LANG: "${{ inputs.base_lang }}"
        FILE_FORMAT: "${{ inputs.file_format }}"
      run: |
        set -e
        
        CMD_PATH="${{ github.action_path }}/bin/store_translation_paths"
        chmod +x "$CMD_PATH"
        $("$CMD_PATH") || {
          echo "Error: store_translation_paths script failed with exit code $?"
          exit 1
        }

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files_from_source_file: lok_action_paths_temp.txt
        separator: ','

    - name: Check if this is the first run on the branch
      if: steps.changed-files.outputs.any_changed == 'false'
      id: check-first-run
      shell: bash
      run: |
        set -e

        if git rev-parse "refs/tags/lokalise-upload-complete" >/dev/null 2>&1; then
          echo "first_run=false" >> $GITHUB_OUTPUT
        else
          echo "first_run=true" >> $GITHUB_OUTPUT
        fi

    - name: Find all translation files
      if: steps.changed-files.outputs.any_changed == 'false' && steps.check-first-run.outputs.first_run == 'true'
      id: find-files
      shell: bash
      env:
        TRANSLATIONS_PATH: "${{ inputs.translations_path }}"
        BASE_LANG: "${{ inputs.base_lang }}"
        FILE_FORMAT: "${{ inputs.file_format }}"
        FLAT_NAMING: "${{ inputs.flat_naming }}"
      run: |
        set -e
        
        CMD_PATH="${{ github.action_path }}/bin/find_all_files"
        chmod +x "$CMD_PATH"
        $("$CMD_PATH") || {
          echo "Error: find_all_files script failed with exit code $?"
          exit 1
        }

    - name: Install Lokalise CLIv2
      if: steps.find-files.outputs.has_files == 'true' || steps.changed-files.outputs.any_changed == 'true'
      uses: bodrovis/install-lokalise-cli-v2@v1.0.2

    - name: Push translation files to Lokalise
      if: steps.find-files.outputs.has_files == 'true' || steps.changed-files.outputs.any_changed == 'true'
      shell: bash
      env:
        BASE_LANG: ${{ inputs.base_lang }}
        CLI_ADD_PARAMS: ${{ inputs.additional_params }}
        MAX_RETRIES: ${{ inputs.max_retries }}
        SLEEP_TIME: ${{ inputs.sleep_on_retry }}
        UPLOAD_TIMEOUT: ${{ inputs.upload_timeout }}
        UPLOAD_POLL_TIMEOUT: ${{ inputs.upload_poll_timeout }}
      run: |
        set -e

        if [ "${{ steps.check-first-run.outputs.first_run }}" == "true" ]; then
          FILES="${{ steps.find-files.outputs.ALL_FILES }}"
        else
          FILES="${{ steps.changed-files.outputs.all_changed_files }}"
        fi

        if [ -z "$FILES" ]; then
          echo "No files to upload."
          exit 1
        fi

        CMD_PATH="${{ github.action_path }}/bin/lokalise_upload"
        chmod +x "$CMD_PATH"

        set +e
        echo "$FILES" | tr ',' '\n' | xargs -P 6 -I {} "$CMD_PATH" "{}" "${{ inputs.project_id }}" "${{ inputs.api_token }}"
        xargs_exit_code=$?
        set -e

        if [ $xargs_exit_code -ne 0 ]; then
          echo "File upload failed"
          exit 1
        fi

    - name: Mark Lokalise upload as complete
      if: steps.check-first-run.outputs.first_run == 'true'
      shell: bash
      run: |
        set -e

        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        if ! git rev-parse "refs/tags/lokalise-upload-complete" >/dev/null 2>&1; then
          git tag -a "lokalise-upload-complete" -m "First Lokalise upload complete"
          git push origin "lokalise-upload-complete"
        else
          echo "Tag 'lokalise-upload-complete' already exists."
        fi